//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFMP.sysmanage
{


    public partial class EmployeeEdit
    {

        /// <summary>
        /// form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txt_SysUserName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltl_SysUserName;

        /// <summary>
        /// txt_RealName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltl_RealName;

        /// <summary>
        /// txt_CellPhone 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltl_CellPhone;

        /// <summary>
        /// ddl_UserState 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltl_UserState;

        /// <summary>
        /// ddl_Department 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddl_DepID;

        protected global::System.Web.UI.WebControls.DropDownList ddl_PostID;

        protected global::System.Web.UI.WebControls.DropDownList ddl_Sex;

        protected global::System.Web.UI.WebControls.DropDownList ddl_Nationality;

        protected global::System.Web.UI.WebControls.DropDownList ddl_Polity;

        protected global::System.Web.UI.WebControls.DropDownList ddl_UserType;

        protected global::System.Web.UI.WebControls.TextBox txt_BirthDate;

        protected global::System.Web.UI.WebControls.TextBox txt_Address;

        protected global::System.Web.UI.WebControls.TextBox txt_JobName;

        protected global::System.Web.UI.WebControls.TextBox txt_HireDate;

        protected global::System.Web.UI.WebControls.TextBox txt_ProbationDays;

        protected global::System.Web.UI.WebControls.TextBox txt_QualifiedDate;

        protected global::System.Web.UI.WebControls.Literal ltl_UserNumber;

        protected global::System.Web.UI.WebControls.FileUpload fl_UpFile;

        protected global::System.Web.UI.WebControls.Image img;

        protected global::System.Web.UI.WebControls.HiddenField hf_UpFile;

        /// <summary>
        /// btn_Submit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btn_Submit;
    }
}
